name: MAUI CI - Android & Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui maui-android

      - name: Restore dependencies
        run: dotnet restore Grocery.App/Grocery.App.csproj

      - name: Build MAUI App (Android)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-android --no-restore /p:TreatWarningsAsErrors=false

      - name: Build MAUI App (Windows)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 --no-restore /p:TreatWarningsAsErrors=false

      - name: Build class libraries
        run: |
          dotnet build Grocery.Core/Grocery.Core.csproj --configuration Release /p:TreatWarningsAsErrors=false
          dotnet build Grocery.Core.Data/Grocery.Core.Data.csproj --configuration Release /p:TreatWarningsAsErrors=false

      - name: Run unit tests
        run: dotnet test --configuration Release --verbosity normal
