name: MAUI CI - Android & Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui maui-android

      # Restore dependencies for Android
      - name: Restore dependencies (Android)
        run: dotnet restore Grocery.App/Grocery.App.csproj

      # Build Android app (warnings ignored)
      - name: Build MAUI App (Android)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-android --no-restore /p:TreatWarningsAsErrors=false /warnasmessage

      # Restore dependencies for Windows with runtime pack
      - name: Restore dependencies (Windows)
        run: dotnet restore Grocery.App/Grocery.App.csproj --runtime win-x64

      # Build Windows app (warnings ignored)
      - name: Build MAUI App (Windows)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win-x64 --no-restore /p:TreatWarningsAsErrors=false /warnasmessage /p:PublishReadyToRun=false

      # Build class libraries (warnings ignored)
      - name: Build class libraries
        run: |
          dotnet build Grocery.Core/Grocery.Core.csproj -c Release /p:TreatWarningsAsErrors=false /warnasmessage
          dotnet build Grocery.Core.Data/Grocery.Core.Data.csproj -c Release /p:TreatWarningsAsErrors=false /warnasmessage

      # Run unit tests
      - name: Run unit tests
        run: dotnet test --configuration Release --verbosity normal
