name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest   # Blijf op Linux (geen iOS support)
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # MAUI 8.0
 
      - name: Installeer alleen Android workload
        run: dotnet workload install maui-android

      # Alleen restore voor Linux-compatibele TFMs
      - name: Herstel afhankelijkheden
        run: dotnet restore --ignore-failed-sources /p:TargetFramework=net8.0-android
 
      - name: Bouw de applicatie (Android)
        run: dotnet build Grocery.App/Grocery.App.csproj -f net8.0-android --configuration Release --no-restore
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-build --verbosity normal
