name: MAUI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui maui-android

      - name: Restore dependencies (Android & Windows)
        run: dotnet restore Grocery.App/Grocery.App.csproj

      - name: Build MAUI App (Android)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-android --no-restore /p:TreatWarningsAsErrors=false

      - name: Build MAUI App (Windows)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win-x64 --no-restore /p:TreatWarningsAsErrors=false /p:PublishReadyToRun=false
