name: MAUI CI - Android Only

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main

jobs:
  android-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Alleen Android workload installeren
      - name: Install MAUI Android workload
        run: dotnet workload install maui-android

      # Restore voor alle projecten, maar alleen Android target (iOS wordt genegeerd)
      - name: Restore all projects (Android only)
        run: dotnet restore /p:TargetFramework=net8.0-android

      # Build class libraries voor Android
      - name: Build class libraries
        run: |
          dotnet build Grocery.Core/Grocery.Core.csproj -f net8.0-android --configuration Release
          dotnet build Grocery.Core.Data/Grocery.Core.Data.csproj -f net8.0-android --configuration Release

      # Build Android-app
      - name: Build Android app
        run: dotnet build Grocery.App/Grocery.App.csproj -f net8.0-android --configuration Release

      # Unit tests uitvoeren
      - name: Run unit tests
        run: dotnet test --configuration Release --verbosity normal
